### ISSUE TITLE
Support wayland

### ISSUE THREAD

**Issue by bakhtiyarneyman** [thingsiplay/emojipick#5]
`xclip` is not available.

**Comment by thingsiplay** [comment]
Added support for Wayland. Now uses `wl-copy` from package `wl-clipboard` under Wayland session, if the option `copy_to_clipboard` is enabled (which is by default). 

While doing so, I rewrote parts of the script and a few little other changes are also done. Such as support for alternative menu system `wofi` under Wayland. That's because I noticed `rofi` and `dmenu` do not support Wayland and run from active terminal under Wayland will send key presses. This is fatal, because it can activate and execute commands not visible to the user. So `wofi` is recommended by me when using this script directly from a terminal.

**Comment by thingsiplay** [comment]
Ok, I'm closing this. Feel free to reopen and comment if there is an issue with Wayland compatibility. In my testing (I'm running Wayland) it works.
